### ISSUE TITLE
Fix speed factors not being truly instant if set to 1

### ISSUE THREAD

**Issue by Calinou** [godot-extended-libraries/godot-interpolated-camera3d#1]
As the TODO says:

https://github.com/Calinou/godot-interpolated-camera3d/blob/76714ffca442abc66d85f32bb32ebf707cd78098/addons/interpolated_camera_3d/interpolated_camera_3d.gd#L34

I always forget how to fix this, even though it should be quite simple. The expected result is that it should behave as if the value wasn't multiplied by `delta` (i.e. using a speed of `1` suppresses any interpolation), but it should remain FPS-independent.

**Comment by matmas** [comment]
With the fix #10 merged this should now be resolved.

Setting speed to `1` now makes the camera follow the target without any interpolation and setting speed to `0` makes the camera stationary as before.
