### ISSUE TITLE
Not Found in Asset Lib

### ISSUE THREAD

**Issue by FeralBytes** [godot-extended-libraries/godot-interpolated-camera3d#3]
Your replacement camera is not found in the Asset Lib when searching from the Editor, nor from the Asset Lib itself.
Searched "lod":
![image](https://user-images.githubusercontent.com/7874274/106551941-c961e080-64c2-11eb-91e4-135934e6f7bf.png)

Searched "Camera" (Found): 
![image](https://user-images.githubusercontent.com/7874274/106552069-0f1ea900-64c3-11eb-8dea-8d3ea8ca2c2c.png)

Searched in Editor for "Camera":
![image](https://user-images.githubusercontent.com/7874274/106552042-062dd780-64c3-11eb-8d90-e412050c39d7.png)

**Comment by FeralBytes** [comment]
Additionally getting this error:

![image](https://user-images.githubusercontent.com/7874274/106552313-8a805a80-64c3-11eb-811c-28b2ffdeac00.png)


![image](https://user-images.githubusercontent.com/7874274/106552395-bbf92600-64c3-11eb-9e31-85e962389193.png)

**Comment by Calinou** [comment]
As stated in the README, this add-on is only for Godot 4.0, not Godot 3.2. This is why it won't show up in the 3.2 editor, and it's also why you're getting a script error :slightly_smiling_face:

**Comment by FeralBytes** [comment]
@Calinou the README.md does not state that the plugin is exclusive to Godot 4.0+. It states that it is a replacement for the Interpolated Camera which will be removed in Godot 4.0. It might be good to make this distinction. 
"This add-on restores a node similar to the built-in InterpolatedCamera3D (which is being removed in Godot 4.0)."
I think you may find others trying to get ahead of deprecation like me. I was hoping to use the replacement now since the warning was popping up to future proof.
Thank you for your time.

**Comment by FeralBytes** [comment]
Thanks @Calinou !
