### ISSUE TITLE
Transform function missing

### ISSUE THREAD

**Issue by padreputativo** [godot-extended-libraries/godot-interpolated-camera3d#5]
res://addons/interpolated_camera_3d/interpolated_camera_3d.gd:41 - Parse Error: Function "Transform()" not found in base self.

**Comment by Calinou** [comment]
Fixed by https://github.com/godot-extended-libraries/godot-interpolated-camera3d/commit/bb5595096fe8ca88e3fa4e97aebb13b08ac6f38b. I updated the asset library listings for version 1.1.0 accordingly (both the plugin and demo).
